### ISSUE TITLE
rx.exceptions.OnErrorNotImplementedException: url == null 

### ISSUE THREAD

**Issue by subhasisbanik** [web3j/quorum#39]
I am facing the below issue when trying to subscribe to events:
at 
rx.exceptions.OnErrorNotImplementedException: url == null 
rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:386) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.util.InternalObservableUtils$ErrorNotImplementedAction.call(InternalObservableUtils.java:383) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeMap$MapSubscriber.onError(OnSubscribeMap.java:88) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.Observable.unsafeSubscribe(Observable.java:10334) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.Observable.subscribe(Observable.java:10423) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.Observable.subscribe(Observable.java:10390) ~[rxjava-1.3.8.jar:1.3.8]
	at rx.Observable.subscribe(Observable.java:10195) ~[rxjava-1.3.8.jar:1.3.8]

Please help!!

**Comment by iikirilov** [comment]
Please provide instruction to reproduce.
