### ISSUE TITLE
basic authentication support

### ISSUE THREAD

**Issue by Freyert** [web3j/quorum#8]
I'm having some trouble using basic authentication. Is the below example not the correct way of using basic auth with this library?

```java
package shmoo.shmoo;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.web3j.protocol.exceptions.ClientConnectionException;
import org.web3j.protocol.http.HttpService;
import org.web3j.quorum.Quorum;

public final class App {

	public static void main(String[] args) {
		try {

			HttpService service = new HttpService("https://xxxx-xxxx-rpc.eu-central-1.kaleido.io");
			service.addHeader("Authorization",
					"Basic xxxxxxxxx");
			service.addHeader("Content-Type", "application/json");
			Quorum quorum = Quorum.build(service);

			String clientVersion = quorum.web3ClientVersion().send().getWeb3ClientVersion();

			System.out.println(clientVersion);

		} catch (IOException | ClientConnectionException ex) {

			Logger.getLogger(App.class.getName()).log(Level.SEVERE, null, ex);

		}
	}

}
```

The error I receive is:

```
org.web3j.protocol.exceptions.ClientConnectionException: Invalid response received: okhttp3.internal.http.RealResponseBody@69ee81fc
	at org.web3j.protocol.http.HttpService.performIO(HttpService.java:114)
	at org.web3j.protocol.Service.send(Service.java:31)
	at org.web3j.protocol.core.Request.send(Request.java:71)
	at shmoo.shmoo.App.main(App.java:22)
```

**Comment by Freyert** [comment]
Here's an example of how one can use basic authentication:

https://github.com/kaleido-io/kaleido-webj-quorum-example/blob/7548cafb148494434503da04bd0dd46b502bca43/src/main/java/kaleido/quorum/App.java#L26-L31
